- 👋 Sup my name is denis and my dream right now is to creat my first game or to perhaps be succesfull when i grow up.  
- 👀 I’m interested in Making my first game
- 🌱 I’m currently learning Unity
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me Discord:denden #8806  
